In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
# To check the demention of the array - ndim
a1.ndim

1

In [5]:
# Length of each dimentsion - shape

a1.shape

(3,)

In [11]:
b1 = np.array([10, 20, 30])
b1

array([10, 20, 30])

In [8]:
b1.ndim

1

In [9]:
b1.shape

(3,)

In [12]:
b2 = np.array([30, 40, 50])
b2

array([30, 40, 50])

In [13]:
b2.ndim

1

In [14]:
b2.shape

(3,)

In [16]:
b3 = np.array([b1, b2])
b3

array([[10, 20, 30],
       [30, 40, 50]])

In [17]:
b3.ndim

2

In [18]:
b3.shape

(2, 3)

In [22]:
b3.size

6

In [23]:
b3.dtype

dtype('int64')

In [19]:
# Two dimensional array is created by passing the list of lists as follow.

a2 = np.array([[1, 2, 3], [3, 4, 5]])
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [20]:
a2.ndim # Two dimensional array 

2

In [21]:
# Two dimensional arrays and the length of inner lists
# Two rows and three columns
# axis 0 is down direction (axis=0)
# axis 1 is cross direction (axis=1)


a2.shape 

(2, 3)

In [ ]:
a3 = np.array([1, 2, 3.3])
a3

In [ ]:
a3.dtype

In [ ]:
a3 = np.array([1, 2, 3.3], dtype=int)
a3

In [ ]:
a4 = np.array([["f", "l", "a", "k", "e"], ["s", "n", "a", "k", "e"], ["a", "w", "a", "k", "e"]])
a4.shape

In [ ]:
# Total elements in the array

a4.size

In [ ]:
# Creating array with arrange()

np.arange(0, 15) # Lower bound 0 is included but upper bound 15 is excluded.

In [ ]:
# Create arrays in step
# Even number arrays

np.arange(0, 15, 2)

In [ ]:
# Create arrays in step
# Odd number arrays

np.arange(1, 15, 2)

In [ ]:
# Creating sequance of real numbers between start and End Point
# np.linespace()
# We specify the number of points

np.linspace(0, 100, 3) # 3 points within 0 to 100


In [ ]:
# Creating without end point

np.linspace(0, 100, 3, endpoint = False)

In [ ]:
### Exercise

np.array([[1],[2],[3],[4]]) # 4 rows and 1 column

In [ ]:
np.array([[1],[2],[3],[4]]).shape

In [ ]:
np.array([[1],[2],[3],[4]]).ndim

In [ ]:
np.array([1,3]).shape

In [ ]:
np.array([1,3]).ndim

In [ ]:
np.array([[1],[3]]).shape

In [ ]:
np.array([[1],[3]]).ndim

In [ ]:
np.array([[1],[3]]).size

In [ ]:
np.array([1,'2',3])

In [ ]:
np.array([1,'2',3]).dtype

## Basic Operations with Arrays

We saw how with the arange() function, we can create an array and specify the range of
numbers that it will contain. Used by itself, this function creates a one-dimensional
array. However, in combination with the reshape() function, we can create an array of
any shape we want.

New array is created. Original arrays are not modified.

In [54]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
a.size

12

In [57]:
a.shape

(12,)

In [59]:
# Transform it in to 4 rows and 3 columns two dimensional arrays
# reshape()

a.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
# We could also obtain for example a three-dimensional array with shape (2,2,3)

a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [42]:
b = np.arange(0, 60)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [43]:
b.size

60

In [69]:
b.ndim

1

In [70]:
c = b.reshape(3, 4, 5) # (Dimension, Row and Column format)

In [71]:
c.ndim

3

In [72]:
c.shape

(3, 4, 5)

In [73]:
d = np.arange(0, 80)

In [74]:
d.shape

(80,)

In [80]:
e = d.reshape(4, 4, 5)
e

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]]])

In [81]:
e.ndim

3

In [ ]:
## Vectorized operationy

## Element wise

A = np.array([[1,1], [0,1]])
A

In [ ]:
A.shape

In [ ]:
A.ndim

In [ ]:
A.size

In [ ]:
B = np.array([[2, 0], [3, 4]])

In [ ]:
B

In [ ]:
# First, let’s use the * operation for numpy arrays:
# Elementwise

A * B

In [ ]:
# We can see that this returned the element-wise product. Now, lets use the dot()
# method:

# Matrix multiplication

A.dot(B)

## Concentinating arrays

default axis is zero

In [ ]:
a = np.array([11, 22])
b = np.array([18, 7, 6])
c = np.array([1, 3, 5])

d = np.concatenate((a, b, c))


In [ ]:
d

In [ ]:
d.ndim

In [ ]:
d.shape

In [ ]:
d.size

In [ ]:
# Concatenating two dimensional arrays

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])


In [ ]:
a

In [ ]:
b

In [ ]:
np.concatenate((a, b), axis = 0) # by row, Taller table, more rows but same columns number

In [ ]:
np.concatenate((a, b), axis = 1) # by column, wider table, same rows but more columns