In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
# To check the demention of the array - ndim
a1.ndim

1

In [4]:
# Length of each dimentsion - shape

a1.shape

(3,)

In [5]:
# Two dimensional array is created by passing the list of lists as follow.

a2 = np.array([[1, 2, 3], [3, 4, 5]])
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [6]:
a2.ndim # Two dimensional array 

2

In [7]:
# Two dimensional arrays and the length of inner lists
# Two rows and three columns
# axis 0 is down direction (axis=0)
# axis 1 is cross direction (axis=1)


a2.shape 

(2, 3)

In [8]:
a3 = np.array([1, 2, 3.3])
a3

array([1. , 2. , 3.3])

In [9]:
a3.dtype

dtype('float64')

In [10]:
a3 = np.array([1, 2, 3.3], dtype=int)
a3

array([1, 2, 3])

In [11]:
a4 = np.array([["f", "l", "a", "k", "e"], ["s", "n", "a", "k", "e"], ["a", "w", "a", "k", "e"]])
a4.shape

(3, 5)

In [12]:
# Total elements in the array

a4.size

15

In [13]:
# Creating array with arrange()

np.arange(0, 15) # Lower bound 0 is included but upper bound 15 is excluded.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
# Create arrays in step
# Even number arrays

np.arange(0, 15, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [15]:
# Create arrays in step
# Odd number arrays

np.arange(1, 15, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [16]:
# Creating sequance of real numbers between start and End Point
# np.linespace()
# We specify the number of points

np.linspace(0, 100, 3) # 3 points within 0 to 100


array([  0.,  50., 100.])

In [17]:
# Creating without end point

np.linspace(0, 100, 3, endpoint = False)

array([ 0.        , 33.33333333, 66.66666667])

In [18]:
### Exercise

np.array([[1],[2],[3],[4]]) # 4 rows and 1 column

array([[1],
       [2],
       [3],
       [4]])

In [19]:
np.array([[1],[2],[3],[4]]).shape

(4, 1)

In [20]:
np.array([[1],[2],[3],[4]]).ndim

2

In [21]:
np.array([1,3]).shape

(2,)

In [22]:
np.array([1,3]).ndim

1

In [23]:
np.array([[1],[3]]).shape

(2, 1)

In [24]:
np.array([[1],[3]]).ndim

2

In [25]:
np.array([[1],[3]]).size

2

In [26]:
np.array([1,'2',3])

array(['1', '2', '3'], dtype='<U21')

In [27]:
np.array([1,'2',3]).dtype

dtype('<U21')

## Basic Operations with Arrays

We saw how with the arange() function, we can create an array and specify the range of
numbers that it will contain. Used by itself, this function creates a one-dimensional
array. However, in combination with the reshape() function, we can create an array of
any shape we want.

New array is created. Original arrays are not modified.

In [28]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
# Transform it in to 4 rows and 3 columns two dimensional arrays
# reshape()

a.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
# We could also obtain for example a three-dimensional array with shape (2,2,3)

a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [33]:
## Vectorized operationy

## Element wise

A = np.array([[1,1], [0,1]])
A

array([[1, 1],
       [0, 1]])

In [34]:
A.shape

(2, 2)

In [35]:
A.ndim

2

In [36]:
A.size

4

In [37]:
B = np.array([[2, 0], [3, 4]])

In [38]:
B

array([[2, 0],
       [3, 4]])

In [39]:
# First, let’s use the * operation for numpy arrays:
# Elementwise

A * B

array([[2, 0],
       [0, 4]])

In [40]:
# We can see that this returned the element-wise product. Now, lets use the dot()
# method:

# Matrix multiplication

A.dot(B)

array([[5, 4],
       [3, 4]])

## Concentinating arrays

default axis is zero

In [41]:
a = np.array([11, 22])
b = np.array([18, 7, 6])
c = np.array([1, 3, 5])

d = np.concatenate((a, b, c))


In [42]:
d

array([11, 22, 18,  7,  6,  1,  3,  5])

In [43]:
d.ndim

1

In [44]:
d.shape

(8,)

In [45]:
d.size

8

In [47]:
# Concatenating two dimensional arrays

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])


In [48]:
a

array([[1, 2],
       [3, 4]])

In [49]:
b

array([[5, 6],
       [7, 8]])

In [50]:
np.concatenate((a, b), axis = 0) # by row, Taller table, more rows but same columns number

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
np.concatenate((a, b), axis = 1) # by column, wider table, same rows but more columns

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])