In [26]:
import numpy as np

In [27]:

a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
b = a # It does not create new object. b is view of a

In [29]:
b

array([0, 1, 2, 3, 4])

In [30]:
b[0]

0

In [31]:
b[0] = 5

In [32]:
b

array([5, 1, 2, 3, 4])

In [33]:
a

array([5, 1, 2, 3, 4])

In [36]:
# Another View by Slicing

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
b = a[:2] #b is the (View of) subset or slice of a
b

array([0, 1])

In [38]:
b[0] = 10

In [39]:
b

array([10,  1])

In [40]:
a # As b is view of a, when b changes in element, a also changes.

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [41]:
# Copy 

aa = np.arange(5)
aa

array([0, 1, 2, 3, 4])

In [42]:
bb = aa.copy()[:2] # copy
bb

array([0, 1])

In [43]:
bb[0] = 10

In [44]:
bb

array([10,  1])

In [45]:
aa

array([0, 1, 2, 3, 4])

## Reshaping

In [46]:
a = np.arange(12)
b = a.reshape(3, 4) # reshape() returns a view of the array, but with a new shape
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
print(a.base)

None


In [48]:
print(b.base)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [49]:
b.base is a

True

In [50]:
b[0] = 10 # First row is changed to 10

In [51]:
a # Underlying base a also changed

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
b

array([[10, 10, 10, 10],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])